// <auto-generated />
using System;
using EchoProject.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EchoProject.Infrastructure.Migrations
{
    [DbContext(typeof(EchoDbContext))]
    [Migration("20260327021955_Pfp")]
    partial class Pfp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EchoProject.Domain.DonationAggregate.Donation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(38,18)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("donor_id");

                    b.Property<string>("FundsReleaseHash")
                        .HasColumnType("text");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(38,18)")
                        .HasColumnName("total_cost");

                    b.Property<string>("TransactionHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_hash");

                    b.Property<Guid?>("TransferredToVendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("transferred_to_vendor_id");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.HasIndex("GoalId");

                    b.HasIndex("TransactionHash")
                        .IsUnique();

                    b.HasIndex("TransferredToVendorId");

                    b.ToTable("donations", (string)null);
                });

            modelBuilder.Entity("EchoProject.Domain.DonationAggregate.DonationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DonationId")
                        .HasColumnType("uuid")
                        .HasColumnName("donation_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("DonationId");

                    b.ToTable("donation_events", (string)null);
                });

            modelBuilder.Entity("EchoProject.Domain.ProjectAggregate.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CostPerUnit")
                        .HasColumnType("decimal(38,18)")
                        .HasColumnName("cost_per_unit");

                    b.Property<decimal>("CurrentAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(38,18)")
                        .HasDefaultValue(0m)
                        .HasColumnName("current_amount");

                    b.Property<Guid>("GoalTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_type_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(38,18)")
                        .HasColumnName("target_amount");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("GoalTypeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("goals", (string)null);
                });

            modelBuilder.Entity("EchoProject.Domain.ProjectAggregate.GoalType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("goal_types", (string)null);
                });

            modelBuilder.Entity("EchoProject.Domain.ProjectAggregate.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string[]>("Images")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("images");

                    b.Property<string>("MainImage")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("main_image_url");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<string>("SmartContractAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("smart_contract_address");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("EchoProject.Domain.ProjectAggregate.ProjectBlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string[]>("Images")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("additional_images");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_blog_posts", (string)null);
                });

            modelBuilder.Entity("EchoProject.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EchoProject.Domain.VendorAggregate.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_id");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decision_date");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("tax_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TypeItemSupply")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type_item_supply");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("Document")
                        .IsUnique();

                    b.ToTable("vendors", (string)null);
                });

            modelBuilder.Entity("goal_vendor", b =>
                {
                    b.Property<Guid>("goal_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("vendor_id")
                        .HasColumnType("uuid");

                    b.HasKey("goal_id", "vendor_id");

                    b.HasIndex("vendor_id");

                    b.ToTable("goal_vendor");
                });

            modelBuilder.Entity("EchoProject.Domain.DonationAggregate.Donation", b =>
                {
                    b.HasOne("EchoProject.Domain.UserAggregate.User", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EchoProject.Domain.ProjectAggregate.Goal", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EchoProject.Domain.VendorAggregate.Vendor", "TransferredToVendor")
                        .WithMany()
                        .HasForeignKey("TransferredToVendorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Donor");

                    b.Navigation("Goal");

                    b.Navigation("TransferredToVendor");
                });

            modelBuilder.Entity("EchoProject.Domain.DonationAggregate.DonationEvent", b =>
                {
                    b.HasOne("EchoProject.Domain.DonationAggregate.Donation", "Donation")
                        .WithMany("Events")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("EchoProject.Domain.ProjectAggregate.Goal", b =>
                {
                    b.HasOne("EchoProject.Domain.ProjectAggregate.GoalType", "GoalType")
                        .WithMany()
                        .HasForeignKey("GoalTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("goal_type_id");

                    b.HasOne("EchoProject.Domain.ProjectAggregate.Project", "Project")
                        .WithMany("Goals")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("project_id");

                    b.Navigation("GoalType");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EchoProject.Domain.ProjectAggregate.Project", b =>
                {
                    b.HasOne("EchoProject.Domain.UserAggregate.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("manager_id");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("EchoProject.Domain.ProjectAggregate.ProjectBlogPost", b =>
                {
                    b.HasOne("EchoProject.Domain.ProjectAggregate.Project", "Project")
                        .WithMany("BlogPosts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EchoProject.Domain.ValueObjects.ImageUrl", "HeaderImage", b1 =>
                        {
                            b1.Property<Guid>("ProjectBlogPostId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("header_image_url");

                            b1.HasKey("ProjectBlogPostId");

                            b1.ToTable("project_blog_posts");

                            b1.WithOwner()
                                .HasForeignKey("ProjectBlogPostId");
                        });

                    b.Navigation("HeaderImage")
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EchoProject.Domain.UserAggregate.User", b =>
                {
                    b.OwnsOne("EchoProject.Domain.ValueObjects.ImageUrl", "ProfilePicture", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("profile_picture_url");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("EchoProject.Domain.ValueObjects.WalletAddress", "WalletAddress", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(42)
                                .HasColumnType("character varying(42)")
                                .HasColumnName("wallet_address");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("EchoProject.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("country_code");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("neighbourhood");

                            b1.Property<int?>("Number")
                                .HasColumnType("integer")
                                .HasColumnName("number");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("zip_code");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("street");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("EchoProject.Domain.ValueObjects.TaxId", "TaxId", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("tax_id");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("ProfilePicture");

                    b.Navigation("TaxId")
                        .IsRequired();

                    b.Navigation("WalletAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("EchoProject.Domain.VendorAggregate.Vendor", b =>
                {
                    b.HasOne("EchoProject.Domain.UserAggregate.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("EchoProject.Domain.ValueObjects.WalletAddress", "Wallet", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(42)
                                .HasColumnType("character varying(42)")
                                .HasColumnName("wallet_address");

                            b1.HasKey("VendorId");

                            b1.ToTable("vendors");

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.Navigation("ApprovedBy");

                    b.Navigation("Wallet")
                        .IsRequired();
                });

            modelBuilder.Entity("goal_vendor", b =>
                {
                    b.HasOne("EchoProject.Domain.ProjectAggregate.Goal", null)
                        .WithMany()
                        .HasForeignKey("goal_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EchoProject.Domain.VendorAggregate.Vendor", null)
                        .WithMany()
                        .HasForeignKey("vendor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EchoProject.Domain.DonationAggregate.Donation", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EchoProject.Domain.ProjectAggregate.Project", b =>
                {
                    b.Navigation("BlogPosts");

                    b.Navigation("Goals");
                });
#pragma warning restore 612, 618
        }
    }
}
